// <auto-generated />
using System;
using MealVendingMachine.MvcWebUI.Entities.Concrete.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MealVendingMachine.MvcWebUI.Migrations
{
    [DbContext(typeof(MealContext))]
    [Migration("20211121114803_MealVendingMachineMigration")]
    partial class MealVendingMachineMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MealVendingMachine.MvcWebUI.Entities.Beverages", b =>
                {
                    b.Property<int>("beverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("beverageId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("beverageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("beverageprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("beverageİmageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("categoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("beverageId");

                    b.ToTable("Beverages");
                });

            modelBuilder.Entity("MealVendingMachine.MvcWebUI.Entities.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("categoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MealVendingMachine.MvcWebUI.Entities.Foods", b =>
                {
                    b.Property<int>("foodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("foodId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("categoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<string>("desription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("foodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("foodprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("foodİmageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("foodId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("MealVendingMachine.MvcWebUI.Entities.Payments", b =>
                {
                    b.Property<int>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("beverageId")
                        .HasColumnType("int")
                        .HasColumnName("beverageId");

                    b.Property<decimal?>("beverageQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("campaigns")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("foodId")
                        .HasColumnType("int")
                        .HasColumnName("foodId");

                    b.Property<decimal?>("foodsQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("paymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("sumprice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("paymentId");

                    b.ToTable("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
